build_wheel_job:
  stage: build

  before_script:
    - echo $CI_JOB_NAME-$CI_JOB_ID
    - echo "Commit tag variable = $CI_COMMIT_TAG"
    - echo "Commit reference name = $CI_COMMIT_REF_NAME"
    - |
      if [[ "$CI_COMMIT_REF_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
         echo "CI_COMMIT_REF_NAME matches a version tag format."
         export IS_VERSION_TAGGED=true
      else
         echo "CI_COMMIT_REF_NAME does NOT match a version tag format."
         export IS_VERSION_TAGGED=false
      fi
      echo "IS_VERSION_TAGGED=$IS_VERSION_TAGGED" > generate_wheel.env
    # Install ulamdyn dependencies from requirements.txt
    - echo GE_JOB_ID=$CI_JOB_ID >> generate_wheel.env
    - make venv
    - source venv/bin/activate

  script:
    # Run the make build command to generate the wheel file
    - VERSION=$(grep VERSION src/ulamdyn/version.py | cut -d "=" -f2)
    - echo "Building package with version $VERSION"
    - make build

  cache:
    # Cache the dist folder where the wheel file is located
    paths:
      - dist/

  artifacts:
    paths:
      - dist/*.whl
    expire_in: 1 week
    reports:
      dotenv: generate_wheel.env

  rules:
    # On other branches, it runs independently
    - if: '$CI_COMMIT_BRANCH != "master"'
      needs: 
        - job: check_lint_job
          artifacts: false
    
    - if: $IS_VERSION_TAGGED == "true"
      when: never

    # On master, the build must wait for version bump to ensure correct versioning
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
      needs: 
        - job: check_lint_job
          artifacts: false
          optional: false
        - job: version_bump_job
          artifacts: true
          optional: false
    - when: never
    
