#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Setup file to install ulamdyn package."""

from __future__ import with_statement
from __future__ import absolute_import

import os
import versioneer
from setuptools import setup, find_packages

DESCRIPTION = "Unsupervised learning analysis for molecular dynamics data"
NAME = "ulamdyn"

if os.path.exists("requirements.txt"):
    requirements = open("requirements.txt").read()
else:
    requirements = (
        ["numpy", "scipy", "h5py", "rmsd", "pandas", "scikit-learn", "tslearn", "joblib"],
    )

if os.path.exists("README.rst"):
    long_description = open("README.rst").read()
else:
    long_description = """ULaMDyn is a data analysis tool, written in Python using the Pandas and Scikit-Learn framework. It provides a set of
                          methods to perform the preprocessing, statistical, and unsupervised learning analysis of data generated by nonadiabatic
                          molecular dynamics simulations. ULaMDyn can automatize the search for hidden patterns in high-dimensional molecular
                          data sets, facilitating the understanding and interpretation of nonadiabatic dynamics simulations."""

# Setting up
setup(
    name=NAME,
    version=versioneer.get_version(),
    cmdclass=versioneer.get_cmdclass(),
    author="Max Pinheiro Jr",
    author_email="<maxjr82@gmail.com>",
    url="www.ulamdyn.com",
    license="LGPLv3",
    description=DESCRIPTION,
    long_description_content_type="text/markdown",
    long_description=long_description,
    packages=find_packages("src"),
    package_dir={"": "src"},
    entry_points={"console_scripts": ["run-ulamdyn=ulamdyn.run_analysis:main"]},
    keywords=[
        "python",
        "chemistry",
        "dimensionality reduction",
        "clustering",
        "molecular dynamics",
    ],
    classifiers=[
        "Development Status :: 2 - Improving code and documentation",
        "Intended Audience :: Computational chemistry",
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    install_requires=requirements,
    extras_require={"modin": ["modin"]},
    python_requires=">=3.9",
)
