#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Setup file to install ulamdyn package."""

import os

from setuptools import find_packages, setup


def get_version(version_filepath: str) -> str:
    """Get the version from version.py file

    Args:
        version_filepath: Path to the version file.

    Returns:
        actual package version

    """
    current_path = os.path.abspath(os.path.dirname(__file__))
    with open(
        os.path.join(current_path, version_filepath), encoding="utf8"
    ) as file:
        version_content = file.read()

    for line in version_content.splitlines():
        if line.startswith("VERSION"):
            delim = '"' if '"' in line else "'"
            return line.split(delim)[1]
    raise RuntimeError("Unable to find version string.")


DESCRIPTION = "Unsupervised learning analysis for molecular dynamics data"
NAME = "ulamdyn"

if os.path.exists("requirements.txt"):
    requirements = open("requirements.txt").read()
else:
    requirements = (
        [
            "numpy",
            "scipy",
            "h5py",
            "rmsd",
            "pandas",
            "scikit-learn",
            "tslearn",
            "joblib",
        ],
    )

if os.path.exists("README.rst"):
    long_description = open("README.rst").read()
else:
    long_description = """ULaMDyn is a data analysis tool, written in Python
                          using the Pandas and Scikit-Learn framework. It
                          provides a set of methods to perform the
                          preprocessing, statistical, and unsupervised learning
                          analysis of data generated by nonadiabatic molecular
                          dynamics (NAMD) simulations. ULaMDyn can automatize
                          the search for hidden patterns in high-dimensional
                          molecular data sets, facilitating the understanding
                          and interpretation of NAMD simulations."""

# Setting up
setup(
    name=NAME,
    version=get_version("src/ulamdyn/version.py"),
    author="Max Pinheiro Jr",
    author_email="<maxjr82@gmail.com>",
    url="www.ulamdyn.com",
    license="LGPLv3",
    description=DESCRIPTION,
    long_description_content_type="text/markdown",
    long_description=long_description,
    packages=find_packages("src"),
    package_dir={"": "src"},
    entry_points={
        "console_scripts": ["run-ulamdyn=ulamdyn.run_analysis:main"]
    },
    keywords=[
        "python",
        "chemistry",
        "dimensionality reduction",
        "clustering",
        "molecular dynamics",
    ],
    classifiers=[
        "Development Status :: 2 - Improving code and documentation",
        "Intended Audience :: Computational chemistry",
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Topic :: Scientific/Engineering :: Physics",
    ],
    install_requires=requirements,
    extras_require={"modin": ["modin"]},
    python_requires=">=3.9",
)
