#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Setup file for the ulamdyn package.
"""

from __future__ import with_statement
from __future__ import absolute_import

import os
from setuptools import setup, find_packages

VERSION = '0.0.2'
DESCRIPTION = 'Unsupervised learning for molecular dynamics data'

if os.path.exists('README.rst'):
    long_description = open('README.rst').read()
else:
    long_description = '''ULaMDyn is a data analysis tool, written in Python using the Pandas and Scikit-Learn framework. It provides a set of
                          methods to perform the preprocessing, statistical, and unsupervised learning analysis of data generated by nonadiabatic
                          molecular dynamics simulations. ULaMDyn can automatize the search for hidden patterns in high-dimensional molecular
                          data sets, facilitating the understanding and interpretation of nonadiabatic dynamics simulations.'''

# Setting up
setup(
    name="ulamdyn",
    version=VERSION,
    author="Max Pinheiro Jr",
    author_email="<maxjr82@gmail.com>",
    url="www.ulamdyn.com",
    license="LGPLv3",
    description=DESCRIPTION,
    long_description_content_type="text/markdown",
    long_description=long_description,
    packages=find_packages('src'),
    package_dir={'': 'src'},
    install_requires=['numpy', 'scipy', 'h5py', 'rmsd', 'pandas', 'scikit-learn', 'joblib'],
    extras_require={'modin': ['modin']},
    keywords=['python', 'chemistry', 'dimensionality reduction', 'clustering', 'molecular dynamics'],
    classifiers=[
        "Development Status :: 2 - Improving code and documentation",
        "Intended Audience :: Computational chemistry",
        "Programming Language :: Python :: 3",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Chemistry",
        "Topic :: Scientific/Engineering :: Physics"
    ],
    python_requires=">=3.7",
)

