## Author: Max Pinheiro Jr <maxjr82@gmail.com>
## Date: March 10 2021
from __future__ import (
    absolute_import,
    division,
    print_function,
    unicode_literals,
    with_statement,
)

import os
import sys
import glob
import rmsd
import h5py
import numpy as np

try:
    import modin.pandas as pd
    import ray

    ray.init()
except ModuleNotFoundError as e:
    import pandas as pd

from itertools import combinations
from ulamdyn.utilities import *


__all__ = ["GetCoords", "GetGradients", "GetProperties"]

#%% Starting the first class: GetCoords
class GetCoords:
    """Class used to read the Cartesian coordinates from Newton-X MD trajectories.

    .. note:: The Cartesian XYZ coordinates can be read either from dyn.out/dyn.xyz
              files generated by the classical NX or from the h5 file of new NX.
              Repeated geometries will be skipped.

    It also provides a function to calculate the root-mean-squared deviation (RMSD)
    between each geometry read from the MD trajectories and a reference geometry.
    Before calculating the RMSD, the two geometries are aligned using the Kabsch algorithm
    (https://en.wikipedia.org/wiki/Kabsch_algorithm).

    This class does not require arguments in its constructor. All the outputs generate by
    the class are given in angstroms.

    Data attributes:
    ----------------
       ``trajectories`` (list): trajectories ID (TRAJXX) available in the working directory.\n
       ``labels`` (np.ndarray): stores the sequence of atom labels.\n
       ``eq_xyz`` (np.ndarray): stores the XYZ matrix of the reference geometry (geom.xyz).\n
       ``xyz`` (np.ndarray): stores the XYZ matrices of all geometries read from the TRAJ directories.\n
       ``rmsd`` (np.ndarray): vector of RMSD values between all geometries and the reference one.\n
       ``dataset`` (pd.dataframe): stores a dataframe of the flattened XYZ matrices.

    """

    # Defining slots to optimize performance (RAM):
    __slots__ = ["trajectories", "labels", "eq_xyz", "xyz", "rmsd", "dataset"]

    def __str__(self):
        return "Data handler class for molecular geometries."

    def __init__(self):
        # This variable contains a list of all available trajectories:
        # [TRAJ1, TRAJ2,..., TRAJN]
        self.trajectories = get_traj_dirs()

        # Store the sequence of atom labels as a numpy array
        self.labels = None
        # Store the XYZ matrix of the reference geometry (np.array)
        self.eq_xyz = None
        # Try to read the reference geometry, geom.xyz file
        # If the file is available, the labels and eq_xyz variables
        # will be update with the data loaded by the function below.
        self.read_eq_geom()

        self.xyz = None
        self.rmsd = None
        self.dataset = None

    @property
    def save_csv(self):
        """Save all loaded geometries (raw format) as a csv file.

        If the RMSD has been calculated, it will be included as an extra column
        in the XYZ coordinates data set.
        """
        if self.dataset is None:
            self.build_dataframe()

        df = self.dataset

        if self.rmsd is not None:
            df["RMSD"] = self.rmsd

        df.to_csv("all_coordinates.csv", index=False, header=True)

    def build_dataframe(self):
        """Create a pandas DataFrame containing the XYZ coordinates from all trajectories.

        After running this function, the class attribute ``dataset`` will be updated with
        the loaded DataFrame object.
        """
        if all(v is not None for v in [self.labels, self.xyz]):
            n_atoms = len(self.labels)
            col_names = [
                ["x" + str(i), "y" + str(i), "z" + str(i)]
                for i in range(1, n_atoms + 1)
            ]
            col_names = sum(col_names, [])
            df = pd.DataFrame(self.xyz.reshape(-1, n_atoms * 3), columns=col_names)

            self.dataset = df

            print("                                                  ")
            print("------------------------------------------------  ")
            print("  The size of the XYZ coordinates data set is\n   ")
            print("     Number of geometries = {}".format(df.shape[0]))
            print("       Number of features = {}".format(df.shape[1]))
            print("------------------------------------------------  ")

        else:
            print("---------------------------------------")
            print("The coordinates variable is empty!")
            print("There is no data available to save.")
            print("Please run the loader functions first.")
            print("---------------------------------------")

    @staticmethod
    def from_h5(outfile):
        """Read the XYZ coordinates from the .h5 file generated by the new Newton-X.

        :param outfile: name of the NX output file, usually dyn.h5
        :type outfile: str
        :return: tuple containing the atom labels and a tensor of size (n_steps, n_atoms, 3)
                 with all XYZ coordinates of one trajectory.
        :rtype: tuple of numpy.arrays
        """
        data = h5py.File(outfile, "r")
        path_to_coords = "particles/all/position/value"
        xyz_geoms = np.array(data[path_to_coords], dtype=np.float64)
        path_to_labels = "particles/all/names"
        atom_labels = np.array(data[path_to_labels], dtype="U")

        return (atom_labels, xyz_geoms)

    def from_dyn(self, outfile):
        """Reads the coordinates from the dyn.out file of Newton-X.

        .. note:: The XYZ coordinates are given in Bohr, and will be converted
                  to Angstrom by the function.

        The number of coordinates to be read will be equal to the number of atoms
        existing in the reference geometry file, geom.xyz. In the case of QM/MM
        calculations, the coordinates of the solvent molecules will be ignored if
        the geom.xyz file contains only the geometry of the solute.

        Args:
           outfile (str): name of the NX output file, dyn.out.

        Returns:

        """
        read_coords = False
        t = -1
        current_time = -1
        num_atoms = np.inf

        xyz_geoms = list()
        atom_labels = list()
        counter = 0

        if self.labels is not None:
            num_atoms = len(self.labels)
            atom_labels = self.labels

        with open(outfile, "r") as dyn_out:
            for line in dyn_out:

                # By keeping track of the current time we can deal with
                # repetitions in restart calculations, but also to deal
                # with switching in QM/MM dynamics.
                if "TIME" in line:
                    current_time = np.float(line.split()[-2])

                if read_coords:
                    vals = line.split()
                    if len(vals) == 6:
                        counter += 1
                        if counter > num_atoms:
                            counter = 0
                            read_coords = False
                            continue
                        coords = np.array(vals[2:5], dtype=np.float64)
                        xyz_geoms.append(coords)
                        # Labels will be read only in the first iteration
                        if current_time == 0.0 and isinstance(atom_labels, list):
                            atom_labels.append(vals[0].upper())
                    else:
                        read_coords = False
                        counter = 0

                # This condition is used to skip repeated geometries.
                if "geometry" in line:
                    if current_time == t:
                        read_coords = False
                    else:
                        read_coords = True
                    t = current_time

        num_atoms = len(atom_labels)

        xyz_geoms = np.array(xyz_geoms)
        xyz_geoms = xyz_geoms.reshape(-1, num_atoms, 3)
        xyz_geoms *= BOHR_TO_ANG
        atom_labels = np.asarray(atom_labels)

        return (atom_labels, xyz_geoms)

    @staticmethod
    def from_xyz(xyzfile):
        """Read the coordinates from the dyn.xyz file of Newton-X."""
        count = 0
        xyz_geoms = list()
        atom_labels = list()

        with open(xyzfile, "r") as inp:
            for line in inp:
                vals = line.split()

                if len(vals) == 1 and count == 0:
                    num_atoms = int(vals[0])

                if len(vals) >= 4:
                    coords = np.array(vals[-3:], dtype=np.float64)
                    coords = coords.reshape(-1, 3)
                    xyz_geoms.append(coords)
                    if count <= num_atoms + 2:
                        atom_labels.append(vals[0])

                count += 1

        atom_labels = np.asarray(atom_labels)
        xyz_array = np.vstack(xyz_geoms).reshape(-1, num_atoms, 3)

        return (atom_labels, xyz_array)

    def read_all_trajs(self):
        """
        Load the XYZ coordinates from all available trajectories, and store the
        values in the class variable ``xyz`` as a numpy array.

        """

        all_geoms = list()
        for trj in self.trajectories:
            print("Reading geometries from %s" % trj + "...")
            results_dir = trj + "/RESULTS/"
            files = os.listdir(results_dir)
            h5file = next((f for f in files if f.endswith(".h5")), None)
            if h5file:
                h5file = results_dir + h5file
                atom_labels, xyz = self.from_h5(h5file)
                all_geoms.append(xyz)
            elif os.path.isfile(results_dir + "dyn.out"):
                dynfile = results_dir + "dyn.out"
                atom_labels, xyz = self.from_dyn(dynfile)
                all_geoms.append(xyz)
            elif os.path.isfile(results_dir + "dyn.xyz"):
                xyzfile = results_dir + "dyn.xyz"
                atom_labels, xyz = self.from_xyz(xyzfile)
                all_geoms.append(xyz)
            else:
                print("\nFile dyn.out or dyn.xyz not available.")
                print("Check the directory %s" % trj + "/RESULTS" + "\n")

        self.xyz = np.concatenate(all_geoms, axis=0)
        self.labels = atom_labels

    def read_eq_geom(self):
        """Read the XYZ coordinates of the reference geometry (geom.xyz),
        and store the values in the class variable ``eq_xyz``.

        """
        try:
            atom_labels, ref_geom = self.from_xyz("geom.xyz")
            self.eq_xyz = np.squeeze(ref_geom, axis=0)
            self.labels = atom_labels
        except FileNotFoundError:
            print("\n-----------------------------------------------------------")
            print("Reference geometry not found!")
            print("The reference geometry is required to compute the RMSD. ")
            print("Check if the geom.xyz file is available in the current dir.")
            print("-----------------------------------------------------------\n")

    @property
    def align_geoms(self):
        """Align the current loaded geometry with respect to the reference geometry
        using the Kabsch algorithm, and computes the corresponding (optimal) RMSD.

        """

        if self.eq_xyz is None:
            self.read_eq_geom()

        self.eq_xyz -= rmsd.centroid(self.eq_xyz)

        if self.xyz is not None:
            xyz_dim = self.xyz.shape
            aligned_geoms = np.empty(xyz_dim, dtype=np.float64)
            rmsd_values = np.empty((xyz_dim[0]), dtype=np.float64)
        else:
            error_msg = "XYZ coordinates not loaded!" + "\n "
            error_msg += "Please make sure that the read_all_trajs function "
            error_msg += "has been executed."
            print(error_msg)
            return

        for idx, geom in enumerate(self.xyz):
            geom -= rmsd.centroid(geom)
            U = rmsd.kabsch(geom, self.eq_xyz)
            geom = np.dot(geom, U)
            geom_rmsd = rmsd.rmsd(self.eq_xyz, geom)
            aligned_geoms[idx] = geom
            rmsd_values[idx] = geom_rmsd

        self.xyz = aligned_geoms
        self.rmsd = rmsd_values


#%% Starting new class: GetGradients
class GetGradients:
    """Class used to read the gradients (forces) from Newton-X MD trajectories.

    This class does not require arguments in its constructor. The outputs generate by
    the class is given in eV/angstrom.

    Data attributes:
    ----------------
       ``trajectories`` (list): trajectories ID (TRAJXX) available in the working directory.\n
       ``all_grads`` (dict): store the gradient matrices (per state) for all MD trajectories.\n
       ``dataset`` (dict): dictionary of dataframes with the flattened gradient matrices.
    """

    # Defining slots to optimize memory access performance (RAM):
    __slots__ = ["trajectories", "all_grads", "datasets"]

    def __str__(self):
        return "Data handler class for atomic forces (gradients)."

    def __init__(self):
        # This variable contains a list of all available trajectories:
        # [TRAJ1, TRAJ2,..., TRAJN]
        self.trajectories = get_traj_dirs()
        # Store the gradient matrices per state as a dictionary, where
        # the key is the state identifier (e.g., {'S1': np.array})
        self.all_grads = dict()
        self.datasets = dict()

    @staticmethod
    def from_h5(outfile):
        """Read the XYZ gradients from the .h5 file generated by the new Newton-X.

        Args:
           outfile (str): name of the NX output file, dyn.h5.

        Returns:

        """
        grads_dict = dict()
        data = h5py.File(outfile, "r")
        path_to_grads = "particles/all/gradients/value"
        xyz_grads = np.array(data[path_to_grads], dtype=np.float64)
        n_states = xyz_grads.shape[-1]

        for state in range(n_states):
            grads_dict[state] = xyz_grads[:, :, :, state]

        return grads_dict

    @staticmethod
    def from_nxlog(outfile):
        """Read all available gradients from the nx.log file of Newton-X."""
        read_grads = False
        current_step = -1
        count_start = 0
        t_current = 0
        t_hop = np.inf

        grads_dict = dict()

        with open(outfile, "r") as nx_log:
            for line in nx_log:

                # This condition is used to monitor the MD restarting, and
                # then skip the repeated gradients (Step 0 of each restart)
                if "STARTING MOLECULAR DYNAMICS" in line:
                    count_start += 1

                if "Nat" in line:
                    num_atoms = np.int(line.split()[-1])

                if "STEP" in line:
                    line_list = line.replace(",", "").split()
                    current_step = np.int(line_list[2])
                    t_current = np.float(line_list[4])

                if "Time of hopping" in line:
                    t_hop = np.float(line.split()[-2])

                # The second condition in the if statement is used to skip
                # the gradients recalculated after hopping
                if ("Gradient" in line) and (t_current != t_hop):
                    if "current" in line:
                        continue
                    elif "state" in line:
                        state = "S" + line.split()[-2]
                    else:
                        state = "current_state"

                    if count_start == 2:
                        read_grads = False
                        count_start -= 1
                    else:
                        read_grads = True

                    if state not in grads_dict:
                        grads_dict[state] = list()
                    continue

                if read_grads:
                    vals = line.split()
                    if len(vals) == 3:
                        grads = np.array(vals, dtype=np.float64)
                        grads_dict[state].append(grads)
                    else:
                        read_grads = False

        for k in grads_dict.keys():
            grads_dict[k] = np.array(grads_dict[k])
            grads_dict[k] = grads_dict[k].reshape(-1, num_atoms, 3)
            grads_dict[k] *= HARTREE_TO_eV / BOHR_TO_ANG

        return grads_dict

    def read_all_trajs(self):
        """Store the gradients read from all trajectories as dictionary."""
        all_grads = dict()
        for trj in self.trajectories:
            print("Reading gradients from %s" % trj + "...")
            files = os.listdir(trj + "/RESULTS")
            h5file = next((f for f in files if f.endswith(".h5")), None)
            if h5file:
                h5file = trj + "/RESULTS/" + h5file
                gradients = self.from_h5(h5file)
                if not all_grads:
                    all_grads = {key: list() for key in gradients.keys()}
                for k in all_grads.keys():
                    all_grads[k].append(gradients[k])
            elif os.path.isfile(trj + "/RESULTS/nx.log"):
                nxfile = trj + "/RESULTS/nx.log"
                gradients = self.from_nxlog(nxfile)
                if not all_grads:
                    all_grads = {key: list() for key in gradients.keys()}
                for k in all_grads.keys():
                    all_grads[k].append(gradients[k])
            else:
                print("\nOutput file nx.log or *.h5 not available.")
                print("Check the directory %s" % trj + "/RESULTS" + "\n")

        for k in all_grads.keys():
            self.all_grads[k] = np.concatenate(all_grads[k], axis=0)

    def build_dataframe(self, save_csv=False):
        """Create and save a pandas dataframe with all available gradients."""

        if not self.all_grads:
            self.read_all_trajs()

        state = list(self.all_grads.keys())[0]
        n_atoms = self.all_grads[state].shape[1]
        col_names = [
            ["Gx" + str(i), "Gy" + str(i), "Gz" + str(i)] for i in range(1, n_atoms + 1)
        ]
        col_names = sum(col_names, [])

        for k in self.all_grads.keys():
            df = pd.DataFrame(
                self.all_grads[k].reshape(-1, n_atoms * 3), columns=col_names
            )
            self.datasets[k] = df
            if save_csv:
                output = "all_gradients_" + k.lower() + ".csv"
                df.to_csv(output, index=False, header=True)


#%% Starting new class: GetProperties
class GetProperties:
    """Class used to read all properties available in the Newton-X MD trajectories.

    This class does not require arguments in its constructor. All the energy quantities
    processed by the class are transformed from Ha to eV. For the other properties, the
    original units used in Newton-X are kept.

    Data attributes:
    ----------------
       ``trajectories`` (list): trajectories ID (TRAJXX) available in the working directory.
       ``dataset`` (pd.dataframe): stores a dataframe with all available properties.
       ``num_states`` (int): keeps track of the number of states considered in the MD simulations.

    Methods:
    --------
       ``save_csv``: saves all loaded properties (energies, oscillator strength and populations)
                     as a csv file.
       ``energies``: reads/processes the total energies from the en.dat file.
       ``oscillator_strength``: if available, reads the oscillator strength from the properties file.
       ``populations``: computes the states populations with data taken from dyn.out file.

    """

    __slots__ = ["trajectories", "dataset", "num_states", "nx_version"]

    def __str__(self):
        return (
            "Data handler class for (quantum/classical) properties of MD trajectories."
        )

    def __init__(self):
        # This variable contains a list of all available trajectories:
        # [TRAJ1, TRAJ2,..., TRAJN]
        self.trajectories = get_traj_dirs()
        # This class variable will be used to store a dataframe
        # with all properties read from the NX outputs
        self.dataset = None
        # Auxiliary variable to keep track of the number of states.
        # The default value will be updated in the energy function.
        self.num_states = None
        # This variable is used to recognize the version of Newton-X (cs or ns),
        # and then use this information to decide which functions should be
        # used to collect the properties data.
        self.nx_version = get_nx_version(self.trajectories[0])

    @property
    def save_csv(self):
        if self.dataset is not None:
            df = self.dataset.copy()
            df["time"] = df["time"].astype(object)

            print("                                             ")
            print("---------------------------------------------")
            print("  The size of the properties data set is\n  ")
            print("    Number of molecules = {}".format(df.shape[0]))
            print("     Number of features = {}".format(df.shape[1]))
            print("---------------------------------------------")

            df.to_csv(
                "all_properties.csv", index=False, header=True, float_format="%.10f"
            )

        else:
            print("The properties variable is empty!")
            print("There is no data to save.")
            print("Please run the loader functions first.")

    def _update_properties(self, df):

        if self.dataset is not None:
            if self.dataset.shape[0] == df.shape[0]:
                if "time" in self.dataset.columns.tolist():
                    dfs_to_merge = (self.dataset, df)
                else:
                    dfs_to_merge = (df, self.dataset)
                self.dataset = pd.concat(dfs_to_merge, axis=1)
            else:
                warning = (
                    "***************************************************************\n"
                )
                warning += "WARNING: The size of the dataframes does not match!\n"
                warning += (
                    "         Please check if there are repeated or missing lines\n"
                )
                warning += "         in one of the data files.\n"
                warning += (
                    "***************************************************************"
                )
                print(warning)
        else:
            print("\n-----------------------------------------------------")
            print("The properties dataset is empty.")
            print("Updating class variable with the current loaded data.")
            print("-----------------------------------------------------\n")
            self.dataset = df

    def _energies_from_h5(self):

        all_energies = list()
        traj_id = list()

        for trj in self.trajectories:
            data = read_h5_nx(trj)
            if data is None:
                continue

            time = np.array(data["observables/potential_energy/time"], dtype=np.float64)
            current_state = np.array(data["observables/nstatdyn/value"], dtype=np.int64)
            epot = np.array(
                data["observables/potential_energy/value"], dtype=np.float64
            )
            etot = np.array(data["observables/total_energy/value"], dtype=np.float64)

            time = time.reshape(-1, 1)
            etot = etot.reshape(-1, 1)
            current_state = current_state.reshape(-1, 1)

            data = np.concatenate((time, epot, etot, current_state), axis=1)

            n_samples = data.shape[0]
            idx = np.int(trj.replace("TRAJ", ""))
            traj_id.append(np.full(n_samples, idx, dtype=np.int))
            all_energies.append(data)

        traj_id = np.concatenate(traj_id)
        traj_id = traj_id.reshape(-1, 1)
        all_energies = np.concatenate(all_energies, axis=0)
        all_energies[:, 1:-1] *= HARTREE_TO_eV

        # The final order of the columns in the array should be like:
        # ['time', 'potential energies', 'total energy', 'current state', 'TRAJ']
        all_energies = np.concatenate((all_energies, traj_id), axis=1)

        return all_energies

    def _energies_from_dat(self):

        all_energies = list()
        traj_id = list()

        for trj in self.trajectories:
            print("Reading energies from %s" % trj + "...")
            try:
                enfile = trj + "/RESULTS/en.dat"
                en = np.loadtxt(enfile)
            except FileNotFoundError:
                print("\n-------------------------------------")
                print("Energy file not found.")
                print("Check the %s/RESULTS directory." % trj)
                print("-------------------------------------\n")
                continue

            all_energies.append(en)
            n_samples = en.shape[0]
            idx = np.int(trj.replace("TRAJ", ""))
            traj_id.append(np.full(n_samples, idx, dtype=np.int))

        traj_id = np.concatenate(traj_id)
        traj_id = traj_id.reshape(-1, 1)
        all_energies = np.concatenate(all_energies, axis=0)
        all_energies[:, 1:] *= HARTREE_TO_eV

        # After swapping the columns, the expected order of the columns should be like:
        # ['time', 'potential energies', 'total energy', 'current state']
        all_energies[:, -1], all_energies[:, -2] = (
            all_energies[:, -2],
            all_energies[:, -1].copy(),
        )
        # And finally we add the column with the indices of the trajectories
        all_energies = np.concatenate((all_energies, traj_id), axis=1)

        return all_energies

    def energies(self):

        if self.nx_version == "cs":
            all_energies = self._energies_from_dat()
        elif self.nx_version == "ns":
            all_energies = self._energies_from_h5()
        else:
            print("ERROR:")
            print("Newton-X version not recognized!")
            return

        self.num_states = all_energies.shape[1] - 4
        state_labels = ["S" + str(i + 1) for i in range(self.num_states)]
        col_names = ["time"] + state_labels + ["Total_Energy", "Current_State", "TRAJ"]
        df = pd.DataFrame(all_energies, columns=col_names)
        df["TRAJ"] = df["TRAJ"].astype(int)

        if self.nx_version == "cs":
            df["State"] = df[state_labels].eq(df["Current_State"], axis=0).idxmax(1)
            df["State"] = df["State"].str.replace("S", "").astype(int)
        elif self.nx_version == "ns":
            df["State"] = df["Current_State"].astype(int)

        # Auxiliary variable used to find the hopping points
        df["State_Next"] = df.groupby(by="TRAJ")["State"].shift(-1, fill_value=-10)

        # Loop to calculate energy difference between all possible pair of states
        for i, j in combinations(state_labels, 2):
            from_to = j.replace("S", "") + i.replace("S", "")
            new_col = "DE" + from_to
            df[new_col] = df[j] - df[i]
            si = np.int(i.replace("S", ""))
            sj = np.int(j.replace("S", ""))
            # Create a binary column to identify hopping geometries
            # The first condition corresponds to hoppings by state decay
            new_col = "Hops_S" + str(sj) + str(si)
            condition = (df["State"] == sj) & (df["State_Next"] == si)
            df[new_col] = np.where(condition, 1, 0)
            # The second condition takes into account upward hoppings
            new_col = "Hops_S" + str(si) + str(sj)
            condition = (df["State"] == si) & (df["State_Next"] == sj)
            df[new_col] = np.where(condition, 1, 0)

        cols_to_drop = state_labels[1:] + ["Current_State", "State_Next"]
        df.drop(cols_to_drop, axis=1, inplace=True)

        # Remove all columns that contains only zeros
        df = df.loc[:, (df != 0).any(axis=0)]

        all_cols = df.columns.tolist()
        base_cols = ["TRAJ", "time", "State", "Total_Energy"]
        cols_reordered = base_cols + list(set(all_cols) - set(base_cols))
        df = df[cols_reordered]

        print("------------------------------------------------")
        print("  The size of the energies data set is\n ")
        print("    Number of geometries = {}".format(df.shape[0]))
        print("      Number of features = {}".format(df.shape[1]))
        print("------------------------------------------------")

        self._update_properties(df)
        df = self.dataset

        return df

    def _os_from_h5(self):

        all_osc_strengths = list()
        for trj in self.trajectories:
            print("Reading oscillator strength from %s" % trj + "...")
            data = read_h5_nx(trj)
            if data is None:
                continue

            osc_traj = np.array(data["observables/oscillator_strengths/value"])
            n_states = osc_traj.shape[-1]
            all_osc_strengths.append(osc_traj)

        all_osc_strengths = np.concatenate(all_osc_strengths, axis=0)
        col_names = ["f_0" + str(state) for state in range(1, n_states + 1)]
        df = pd.DataFrame(all_osc_strengths, columns=col_names)

        return df

    def _os_from_txt(self):

        for trj in self.trajectories:
            step = -1
            counter = -1
            read_line = False

            print("Reading oscillator strength from %s" % trj + "...")
            try:
                propfile = trj + "/RESULTS/properties"
                f = open(propfile, "r")
            except:
                print("\n---------------------------------------")
                print("Properties file not found or corrupted.")
                print("Check the %s/RESULTS directory." % trj)
                print("---------------------------------------\n")
                continue

            lines = f.read()
            if "Oscillator strength" not in lines:
                f.close()
                print("\nOscillator strength not found in %s" % propfile)
                return
            else:
                lines = lines.split("\n")

                oscillator_lines = list(
                    filter(lambda x: x.startswith(" Oscillator "), lines)
                )
                time_lines = list(filter(lambda x: x.startswith(" TIME "), lines))
                time_lines = list(set([float(i.split()[2]) for i in time_lines]))
                num_rows = len(time_lines)
                osc_dict = dict()
                for line in oscillator_lines:
                    states = line.split()[2]
                    if states not in osc_dict.keys():
                        osc_dict[states] = np.full(num_rows, np.nan)

                # Start reading the properties file
                for line in lines:
                    if "STEP:" in line:
                        current_step = np.int(line.split()[4])
                        if current_step != step:
                            read_line = True
                            counter += 1
                        else:
                            read_line = False
                        step = current_step

                    if ("Oscillator" in line) and read_line:
                        x = np.float(line.split()[4])
                        states = line.split()[2]
                        osc_dict[states][counter] = x

            f.close()

        col_names = [
            "f_" + "".join(key.replace("(", "").replace(")", "").split(","))
            for key in osc_dict
        ]
        df = pd.DataFrame(osc_dict)
        df.columns = col_names

        return df

    def oscillator_strength(self):

        if self.nx_version == "cs":
            df = self._os_from_txt()
        elif self.nx_version == "ns":
            df = self._os_from_h5()
        else:
            print("ERROR:")
            print("Newton-X version not recognized!")
            return

        self._update_properties(df)
        df = self.dataset

        return df

    def _populations_from_h5(self):

        all_populations = list()

        for trj in self.trajectories:
            print("Reading populations from %s" % trj + "...")
            data = read_h5_nx(trj)
            if data is None:
                continue

            pop_traj = np.array(data["observables/populations/value"], dtype=np.float64)
            all_populations.append(pop_traj)

        all_populations = np.concatenate(all_populations, axis=0)

        return all_populations

    def _populations_from_txt(self):

        coefs_list = list()

        for trj in self.trajectories:

            print("Reading populations from %s" % trj + "...")
            try:
                dynfile = trj + "/RESULTS/dyn.out"
                f = open(dynfile, "r")
            except FileNotFoundError:
                print("\n-------------------------------------------------")
                print("The file dyn.out was not found or is corrupted.")
                print("Check the %s/RESULTS directory." % trj)
                print("-------------------------------------------------\n")
                continue

            n_states = 0
            lines = f.readlines()
            # Start reading the properties file
            for line in lines:
                if "STEP" in line:
                    current_step = np.int(line.split()[1])
                if " Wave function state " in line:
                    coefs = list(np.float_(line.split()[-2:]))
                    coefs_list.append(coefs)
                    if current_step == 0:
                        n_states += 1

        coefs_list = np.array(coefs_list, dtype=np.float64)
        all_populations = np.sum(coefs_list ** 2, axis=1).reshape(-1, n_states)

        return all_populations

    def populations(self):

        if self.nx_version == "cs":
            all_populations = self._populations_from_txt()
        elif self.nx_version == "ns":
            all_populations = self._populations_from_h5()
        else:
            print("ERROR:")
            print("Newton-X version not recognized!")
            return

        ncols = all_populations.shape[1]
        col_names = ["Pop" + str(i) for i in range(1, ncols + 1)]
        df = pd.DataFrame(all_populations, columns=col_names)

        self._update_properties(df)
        df = self.dataset

        return df
