## Author: Max Pinheiro Jr <maxjr82@gmail.com>
## Date: March 10 2021
from __future__ import (
    absolute_import,
    division,
    print_function,
    unicode_literals,
    with_statement,
)

import os
import sys
import h5py
import numpy as np

try:
    import modin.pandas as pd

except ModuleNotFoundError as e:
    import pandas as pd

from scipy.fftpack import fft, fftfreq
from scipy.ndimage.filters import gaussian_filter1d as gaussian

from ulamdyn.utilities import *

__all__ = ["GetVelocities", "KineticEnergy", "VibrationalSpectra"]

#%% Starting the first class: GetVelocities
class GetVelocities:
    """Class used to collect velocities from all MD trajectories of Newton-X."""

    # Defining slots to optimize performance (RAM):
    __slots__ = ["trajectories", "n_atoms", "veloc"]

    def __repr__(self) -> str:
        """Provide a string representation of the class.

        :return: Short description of the class functionality.
        :rtype: str
        """
        return "Data handler class for NX-MD velocities."

    def __init__(self, n_atoms=None):
        """Class initializer."""
        # This variable contains a list of all available trajectories:
        # [TRAJ1, TRAJ2,..., TRAJN]
        self.trajectories = check_nx_trajs()

        if n_atoms == None:
            self.n_atoms = get_num_atoms()
        else:
            self.n_atoms = int(n_atoms)

        self.veloc = None

    def from_dyn(self, outfile: str, tmax=100000) -> np.ndarray:
        """Read velocities from a single trajectory of Newton-X.

        .. note:: The final velocities dataset will contains information only for the first
                  set of n_atoms, as defined by the class attribute :attr:`~ulamdyn.GetVelocities.n_atoms`.

        :param outfile: name of the NX output file containing the velocities, dyn.out.
        :type outfile: str
        :return: tensor of shape (n_steps, n_atoms, 3) with all velocities data.
        :rtype: numpy.ndarray
        """
        t = -1
        read_veloc = False
        n_atoms = self.n_atoms

        f = open(outfile, "r")
        lines = f.read()

        if "velocity" not in lines:
            f.close()
            print("\nThe %s file does not contain information of velocities." % outfile)
            return
        else:
            lines = lines.split("\n")

            veloc_lines = list(filter(lambda k: "velocity" in k, lines))
            n_rows = len(veloc_lines)
            # veloc = np.empty((n_rows, n_atoms, 3), dtype=np.float64)
            veloc = []
            count_atoms = 0
            count_steps = -1

            for line in lines:

                if "TIME" in line:
                    current_time = np.float(line.split()[-2])
                    if current_time > tmax:
                        break

                if read_veloc:
                    vals = line.split()
                    if len(vals) == 3:
                        if count_atoms == n_atoms:
                            count_atoms = 0
                            read_veloc = False
                            continue
                        # veloc[count_steps][count_atoms] = np.array(
                        #    vals, dtype=np.float64
                        # )
                        veloc.append(vals)
                        count_atoms += 1
                    else:
                        count_atoms = 0
                        read_veloc = False

                if "velocity" in line:
                    if current_time == t:
                        read_veloc = False
                    else:
                        read_veloc = True
                    t = current_time
                    count_steps += 1

        f.close()

        veloc = np.vstack(veloc).reshape(-1, n_atoms, 3)

        return veloc

    def from_h5(self, outfile: str) -> np.ndarray:
        """Read velocities from the .h5 file generated by the new Newton-X.

        .. note:: The full velocities dataset will be sliced to select only the first
                  set of n_atoms, as defined by the class attribute :attr:`~ulamdyn.GetVelocities.n_atoms`.

        :param outfile: name of the NX output file, usually dyn.h5.
        :type outfile: str
        :return: tensor of shape (n_steps, n_atoms, 3) with all velocities data.
        :rtype: numpy.ndarray
        """
        data = h5py.File(outfile, "r")
        path_to_veloc = "particles/all/velocities/value"
        veloc = np.array(data[path_to_veloc], dtype=np.float64)

        # Slice the final array to select the first n_atoms
        veloc = veloc[:, : self.n_atoms, :]

        return veloc

    def read_all_trajs(self):
        """Concatenate the XYZ velocities read from all available MD trajectories.

        After running this method, the class attribute :attr:`~ulamdyn.GetVelocities.veloc`
        will be updated with the full dataset of velocities read from the Newton-X output files.
        """
        all_veloc = list()
        for trj in self.trajectories:
            print("Reading velocities from %s" % trj + "...")
            tmax = self.trajectories.get(trj)
            results_dir = trj + "/RESULTS/"
            files = os.listdir(results_dir)
            h5file = next((f for f in files if f.endswith(".h5")), None)
            if h5file:
                h5file = results_dir + h5file
                veloc = self.from_h5(h5file)
            elif os.path.isfile(results_dir + "dyn.out"):
                dynfile = results_dir + "dyn.out"
                veloc = self.from_dyn(dynfile, tmax)
            else:
                print("\nNX output file not found.")
                print("Check the directory %s" % trj + "/RESULTS" + "\n")
                continue
            all_veloc.append(veloc)

        all_veloc = np.concatenate(all_veloc, axis=0)
        self.veloc = all_veloc

    @classmethod
    def from_all_trajs(cls, n_atoms=None):
        """Wrapper function to collect the MD velocities without instantiating the class.

        :param n_atoms: define the total number of atoms to consider in the velocities dataset,
                        defaults to None. If None, the value will be taken from the geom.xyz file.
        :type n_atoms: int, optional
        :return: the full velocities data set given as a tensor of shape (n_steps, n_atoms, 3).
        :rtype: numpy.ndarray
        """
        instance = cls(n_atoms)
        instance.read_all_trajs()
        veloc = instance.veloc
        return veloc


class KineticEnergy:
    """Class used to calculate the atomic or molecular components of the MD kinetic energy."""

    # Defining slots to optimize performance (RAM):
    __slots__ = ["trajectories", "n_atoms", "energies", "atom_mass", "atom_labels"]

    def __repr__(self):
        return "Kinetic energy calculator."

    def __init__(self, n_atoms=None) -> None:
        """Class constructor.

        :param n_atoms: total number of atoms to filter the velocities dataset before calculating
                        the kinetic energies, defaults to None. If None, the value will be taken
                        from the geom.xyz file.
        :type n_atoms: int, optional
        """
        self.trajectories = get_traj_dirs()
        if n_atoms == None:
            self.n_atoms = get_num_atoms()
        else:
            self.n_atoms = int(n_atoms)

        self.energies = None
        self.atom_labels, self.atom_mass = get_labels_masses(
            list(self.trajectories)[0], self.n_atoms
        )

    @staticmethod
    def _atom_speed(veloc_xyz: np.ndarray):
        """Calculate the speed of every atom in the molecular system."""
        return np.linalg.norm(veloc_xyz, axis=2)

    def calc_per_atom(self) -> np.ndarray:
        """Calculate the kinetic energy of each atom for all MD trajectories available.

        :return: matrix with the kinetic energy of the selected atoms arranged in columns.
        :rtype: numpy.ndarray
        """
        all_veloc = GetVelocities.from_all_trajs(self.n_atoms)
        all_speeds = self._atom_speed(all_veloc)
        v_squared = all_speeds**2
        all_ekin_atoms = 0.5 * np.multiply(v_squared, self.atom_mass)
        all_ekin_atoms *= HARTREE_TO_eV

        return all_ekin_atoms

    def calc_per_molecule(
        self, n_mols_per_type: list, n_atoms_per_mol: list
    ) -> np.ndarray:
        """Sum the atomic contributions of kinetic energy for each molecule.

        .. note:: In the current version, this function only supports two different types of
                  molecules in the geom file, where the first set of atoms in the geom file
                  should always correspond to the solute. The function will be generalized in
                  future versions to support any number of different molecules.

        :param n_mols_per_type: give the number of molecules in each one of the two subsystems,
                                typically one solute and several solvent molecules as in QM/MM.
        :type n_mols_per_type: list
        :param n_atoms_per_mol: how many atoms exist in each molecular subsystem.
        :type n_atoms_per_mol: list
        :return: a matrix of shape (n_samples, n_mols_1 + n_mols_2) with the kinetic energy of
                 each molecule in the system arranged in columns.
        :rtype: numpy.ndarray
        """
        n_mols1, n_mols2 = n_mols_per_type
        n_atoms1, n_atoms2 = n_atoms_per_mol

        all_ekin_atoms = self.calc_per_atom()
        # Here we assume that the first n_atoms1 in the geom file of NX
        # corresponds to the solute molecule. Therefore, we slice the
        # all_ekin_atoms matrix using the n_atoms1 variable.
        ekin_solute = all_ekin_atoms[:, :n_atoms1]
        ekin_solute = ekin_solute.sum(axis=1, keepdims=True)
        ekin_solvent = all_ekin_atoms[:, n_atoms1:]
        ekin_solvent = ekin_solvent.reshape(-1, n_mols2, n_atoms2).sum(axis=2)
        ekin_molecules = np.concatenate((ekin_solute, ekin_solvent), axis=1)

        return ekin_molecules

    def build_dataframe(
        self,
        discretization_level="atom",
        n_mols_per_type=None,
        n_atoms_per_mol=None,
        save_csv=False,
    ):
        """Create a dataset containing the kinetic energies splitted by atoms or molecules.

        :param discretization_level: how to split the kinetic energy, defaults to "atom"
        :type discretization_level: str, optional
        :param n_mols_per_type: number of molecules per subsystem, typically one solute and
                                several solvent molecules as in QM/MM, defaults to None.
        :type n_mols_per_type: int, optional
        :param n_atoms_per_mol: number of atoms in each molecular subsystem, defaults to None.
        :type n_atoms_per_mol: int, optional
        :param save_csv: export the dataset with the computed kinetic energies as a csv file,
                         defaults to False
        :type save_csv: bool, optional
        :return: a structured dataset with the values of kinetic energies computed for all
                 trajectories, where each row corresponds to one time step of a given trajectory
                 and the columns refer to the discretization level (atoms or molecules).
        :rtype: pandas.DataFrame | modin.pandas.dataframe.DataFrame
        """
        if discretization_level == "atom":
            all_ekin = self.calc_per_atom()
            atom_id = np.arange(1, len(self.atom_labels) + 1)
            col_names = [
                "Ekin_" + label + str(n) for label, n in zip(self.atom_labels, atom_id)
            ]
        elif discretization_level == "molecule":
            if None not in [n_mols_per_type, n_atoms_per_mol]:
                all_ekin = self.calc_per_molecule(n_mols_per_type, n_atoms_per_mol)
                n_mols = all_ekin.shape[1]
                col_names = ["Ekin_mol" + str(n + 1) for n in range(n_mols)]
            else:
                print("--------------------------------------------------------------")
                print("ERROR:")
                print("A list with the number of molecules per type, and the")
                print("corresponding number of atoms per different molecule")
                print("must be provided to calculate the kinetic energy per molecule")
                print("--------------------------------------------------------------")
                return

        df = pd.DataFrame(all_ekin, columns=col_names)

        if save_csv:
            df.to_csv("all_kinetic_energies.csv", index=False, header=True)

        return df


#%% Starting the third class: VibrationalSpectra
class VibrationalSpectra(GetVelocities):
    """Calculate the vibrational density of states for each MD trajectory."""

    def __init__(self, n_atoms=None) -> None:
        """Class initializer."""
        super().__init__(n_atoms=n_atoms)
        self.spectrum = None
        self.mass = get_labels_masses(list(self.trajectories)[0], n_atoms)[1]
        self.dt = self._get_time_step

    @property
    def _get_time_step(self):

        control = read_nx_control(list(self.trajectories)[0])
        dt = control.get("dt")
        return dt

    @staticmethod
    def calc_pdos(Vel, dt, mass=None):
        """Calculate the power spectrum of the velocity auto-correlation function.

        :param Vel: tensor of shape (n_steps, n_atoms, 3) with atomic velocities collected
                    from a single MD trajectory.
        :type Vel: numpy.ndarray
        :param dt: time step used to integrate the classical equations.
        :type dt: float
        :param mass: if provided, rescale the velocities by the atomic mass of each
                     specie; the default is None.
        :type dt: numpy.ndarray
        :return: two-columns array containing the calculated frequencies (cm^-1) in the
                 first columns and the density of states in the second one (a.u.)
        :rtype: numpy.ndarray
        """
        if mass is not None:
            mass = mass.reshape(-1, 1)
            Vel = mass * Vel

        n_steps = Vel.shape[0]
        Vel = Vel.reshape(n_steps, -1).T

        # mean velocity auto-correlation for all degrees of freedom
        vac2 = [np.correlate(v, v, "full") for v in Vel]
        vac2 /= np.linalg.norm(vac2, axis=1)[:, None]
        vac2 = np.mean(vac2, axis=0)

        # power spectrum (vibrational density of states)
        pdos = np.abs(fft(vac2)) ** 2
        pdos /= np.linalg.norm(pdos) / 2

        # Convert the frequencies from Petahertz to cm^-1
        freq = fftfreq(2 * n_steps - 1, dt) * 33356.4095198152

        freq = freq[:n_steps]
        pdos = pdos[:n_steps]

        # pdos = gaussian(pdos, sigma=50)

        traj_spec = np.array([freq, pdos]).T

        return traj_spec

    def calc_all_trajs(self, mass_weighted=True):
        """Calculate the vibrational spectra for each MD trajectory."""

        all_vib_spec = list()
        mass = None
        dt = self.dt

        if mass_weighted:
            mass = self.mass

        for trj in self.trajectories:
            print("Computing power spectra for %s" % trj + "...")
            results_dir = trj + "/RESULTS/"
            files = os.listdir(results_dir)
            h5file = next((f for f in files if f.endswith(".h5")), None)
            if h5file:
                h5file = results_dir + h5file
                veloc = self.from_h5(h5file)
            elif os.path.isfile(results_dir + "dyn.out"):
                dynfile = results_dir + "dyn.out"
                veloc = self.from_dyn(dynfile)
            else:
                print("\nNX output file not found.")
                print("Check the directory %s" % trj + "/RESULTS" + "\n")
                continue

            spec = self.calc_pdos(veloc, dt, mass)
            all_vib_spec.append(spec)

        all_vib_spec = np.concatenate(all_vib_spec, axis=0)
        self.spectrum = all_vib_spec

    def build_dataframe(self, save_csv=False):
        """Create a dataset with information of vibrational spectra per MD trajectory.

        :param save_csv: if True, export the dataset with the computed spectra to a csv
                         file, defaults to False.
        :type save_csv: bool, optional
        :return: two-columns dataframe storing the vibrational frequencies (cm^-1) in the
                 first columns and the density of states in the second one (a.u.)
        :rtype: pandas.DataFrame | modin.pandas.dataframe.DataFrame
        """
        if self.spectrum is None:
            self.calc_all_trajs()

        col_names = ["Freq", "DOS"]
        df = pd.DataFrame(self.spectrum, columns=col_names)

        if save_csv:
            df.to_csv("all_vibrational_spectra.csv", index=False, header=True)

        return df
