"""Module with auxiliary functions and constants used to process JKSH data."""

# Author: Aneshka Moudry <aneshkamoudry@gmail.com>
# Date: Feb 6 2025

import glob
import os
from typing import Tuple

import h5py
import numpy as np
import json

__all__ = [
    "BOHR_TO_ANG",
    "HARTREE_TO_KCAL",
    "HARTREE_TO_eV",
    "PROTON_MASS",
    "AU_TO_FS",
    "get_traj_dirs",
    "get_nx_version",
    "get_labels_masses",
    "read_nx_control",
    "read_h5_nx",
    "get_num_atoms",
    "check_nx_trajs",
] 
# %% List of constants
BOHR_TO_ANG = 0.529177210903
HARTREE_TO_KCAL = 627.5096080305927
HARTREE_TO_eV = 27.211399
PROTON_MASS = 1822.888515
# Convert t from atomic units to femtosecond
AU_TO_FS = 2.418884326509 * 10 ** (-2)

# %% Dictionary of elements

ELEMENT_NAMES = {
    1: "H",
    2: "He",
    3: "Li",
    4: "Be",
    5: "B",
    6: "C",
    7: "N",
    8: "O",
    9: "F",
    10: "Ne",
    11: "Na",
    12: "Mg",
    13: "Al",
    14: "Si",
    15: "P",
    16: "S",
    17: "Cl",
    18: "Ar",
    19: "K",
    20: "Ca",
    21: "Sc",
    22: "Ti",
    23: "V",
    24: "Cr",
    25: "Mn",
    26: "Fe",
    27: "Co",
    28: "Ni",
    29: "Cu",
    30: "Zn",
    31: "Ga",
    32: "Ge",
    33: "As",
    34: "Se",
    35: "Br",
    36: "Kr",
    37: "Rb",
    38: "Sr",
    39: "Y",
    40: "Zr",
    41: "Nb",
    42: "Mo",
    43: "Tc",
    44: "Ru",
    45: "Rh",
    46: "Pd",
    47: "Ag",
    48: "Cd",
    49: "In",
    50: "Sn",
    51: "Sb",
    52: "Te",
    53: "I",
    54: "Xe",
    55: "Cs",
    56: "Ba",
    57: "La",
    58: "Ce",
    59: "Pr",
    60: "Nd",
    61: "Pm",
    62: "Sm",
    63: "Eu",
    64: "Gd",
    65: "Tb",
    66: "Dy",
    67: "Ho",
    68: "Er",
    69: "Tm",
    70: "Yb",
    71: "Lu",
    72: "Hf",
    73: "Ta",
    74: "W",
    75: "Re",
    76: "Os",
    77: "Ir",
    78: "Pt",
    79: "Au",
    80: "Hg",
    81: "Tl",
    82: "Pb",
    83: "Bi",
    84: "Po",
    85: "At",
    86: "Rn",
    87: "Fr",
    88: "Ra",
    89: "Ac",
    90: "Th",
    91: "Pa",
    92: "U",
    93: "Np",
    94: "Pu",
    95: "Am",
    96: "Cm",
    97: "Bk",
    98: "Cf",
    99: "Es",
    100: "Fm",
    101: "Md",
    102: "No",
    103: "Lr",
    104: "Rf",
    105: "Db",
    106: "Sg",
    107: "Bh",
    108: "Hs",
    109: "Mt",
    110: "Ds",
    111: "Rg",
    112: "Cn",
    114: "Uuq",
    116: "Uuh",
}

ELEMENT_WEIGHTS = {
    1: 1.00797,
    2: 4.00260,
    3: 6.941,
    4: 9.01218,
    5: 10.81,
    6: 12.011,
    7: 14.0067,
    8: 15.9994,
    9: 18.998403,
    10: 20.179,
    11: 22.98977,
    12: 24.305,
    13: 26.98154,
    14: 28.0855,
    15: 30.97376,
    16: 32.06,
    17: 35.453,
    19: 39.0983,
    18: 39.948,
    20: 40.08,
    21: 44.9559,
    22: 47.90,
    23: 50.9415,
    24: 51.996,
    25: 54.9380,
    26: 55.847,
    28: 58.70,
    27: 58.9332,
    29: 63.546,
    30: 65.38,
    31: 69.72,
    32: 72.59,
    33: 74.9216,
    34: 78.96,
    35: 79.904,
    36: 83.80,
    37: 85.4678,
    38: 87.62,
    39: 88.9059,
    40: 91.22,
    41: 92.9064,
    42: 95.94,
    43: 98,
    44: 101.07,
    45: 102.9055,
    46: 106.4,
    47: 107.868,
    48: 112.41,
    49: 114.82,
    50: 118.69,
    51: 121.75,
    53: 126.9045,
    52: 127.60,
    54: 131.30,
    55: 132.9054,
    56: 137.33,
    57: 138.9055,
    58: 140.12,
    59: 140.9077,
    60: 144.24,
    61: 145,
    62: 150.4,
    63: 151.96,
    64: 157.25,
    65: 158.9254,
    66: 162.50,
    67: 164.9304,
    68: 167.26,
    69: 168.9342,
    70: 173.04,
    71: 174.967,
    72: 178.49,
    73: 180.9479,
    74: 183.85,
    75: 186.207,
    76: 190.2,
    77: 192.22,
    78: 195.09,
    79: 196.9665,
    80: 200.59,
    81: 204.37,
    82: 207.2,
    83: 208.9804,
    84: 209,
    85: 210,
    86: 222,
    87: 223,
    88: 226.0254,
    89: 227.0278,
    91: 231.0359,
    90: 232.0381,
    93: 237.0482,
    92: 238.029,
    94: 242,
    95: 243,
    97: 247,
    96: 247,
    102: 250,
    98: 251,
    99: 252,
    108: 255,
    109: 256,
    100: 257,
    101: 258,
    103: 260,
    104: 261,
    107: 262,
    105: 262,
    106: 263,
    110: 269,
    111: 272,
    112: 277,
}
# %% Auxiliary functions

def get_traj_dirs() -> list:
    """Generate a list of TRAJ directories to be processed.

    :return: A list with the name of all 'run_x*' directories (sorted in
             ascending order) generated by the JKSH simulations available in the
             current directory.
    :rtype: list
    """
    dirs_list = glob.glob("run_x[0-9]*")
    dirs_list = sorted(dirs_list, key=lambda x: int(x.rsplit("run_x")[1]))
    return dirs_list


def get_labels_masses(
    traj_dir: str, n_atoms: int = None
) -> Tuple[np.ndarray, np.ndarray]:
    """Extract the atom labels and atomic masses from the JKSH geometry input.

    :param traj_dir: Name of the TRAJ directory from which the geometry file
                     will be read.
    :type traj_dir: str
    :param n_atoms: If provided, the first n_atoms of the XYZ coordinates
                    matrix will be selected and returned, defaults to None.
    :type n_atoms: _type_, optional
    :return: Two separate numpy arrays containing the atom labels and the
             respective masses.
    :rtype: Tuple[np.ndarray, np.ndarray]
    """
    if os.path.isfile(traj_dir + "/geom.xyz"):
        # This is the standard geom input file in JKSH
        nx_geom_file = traj_dir + "/geom.xyz"
    else:
        geom_missing_error = (
            "--------------------------------------------------------------\n"
        )
        geom_missing_error += (
            "ERROR:                                                       \n"
        )
        geom_missing_error += (
            "JKSH geometry file not found.                            \n"
        )
        geom_missing_error += (
            "Check the content of the {} directory \n".format(traj_dir)
        )
        geom_missing_error += (
            "--------------------------------------------------------------\n"
        )
        raise FileNotFoundError(geom_missing_error)

    try:
        data = np.loadtxt(
            nx_geom_file,
            skiprows=2, 
            usecols=(0,),
            unpack=True,
            dtype="U2",
        )
        atom_labels = data

        atomic_numbers = []
        for label in atom_labels:
            for num, symbol in ELEMENT_NAMES.items():
                if symbol == label:
                    atomic_numbers.append(num)
                    break

        atomic_numbers = np.array(atomic_numbers)
        atom_mass = np.array([ELEMENT_WEIGHTS[num] for num in atomic_numbers])
        atom_mass *= PROTON_MASS
        
    except IndexError as ind_err:
        raise (ind_err)
    except ValueError as val_err:
        raise (val_err)

    if n_atoms:
        atom_labels = atom_labels[:n_atoms]
        atom_mass = atom_mass[:n_atoms]

    return (atom_labels, atom_mass)


def read_nx_control(traj_dir: str) -> dict:
    """Read and store the JKSH simulation settings from the .json file.

    :param traj_dir: Name of the TRAJ directory from which the geometry file
                     will be read.
    :type traj_dir: str
    :return: Dictionary with all keywords and corresponding values
             read from the .json file
    :rtype: dict
    """
    control = {}
    try:
        json_files = [f for f in os.listdir(traj_dir) if f.endswith('.json')]
        if json_files:
            control_input = traj_dir + "/" + json_files[0]
        else:
            print(f"No .json files found in {traj_dir}")
    except FileNotFoundError:
        print(f"Directory not found: {traj_dir}")

        return control
    
    import json

    with open(control_input, "r", encoding="utf-8") as nxinp:
        try:
            control = json.load(nxinp)
            return control
        except json.JSONDecodeError:
            print(f"Error: {control_input} is not a valid JSON file")
        return {}
    

def get_num_atoms() -> int:
    """Get the number of atoms from a reference 'geom.xyz' file.

    :return: The number of atoms in a molecule or fragment of it.
    :rtype: int
    """
    try:
        n_atoms = int(open("geom.xyz").readline().rstrip())
        return n_atoms
    except FileNotFoundError as exc:
        geom_missing_error = (
            "--------------------------------------------------------------\n"
        )
        geom_missing_error += (
            "ERROR:                                                       \n"
        )
        geom_missing_error += (
            "Reference geometry file (geom.xyz) not found.                \n"
        )
        geom_missing_error += "Check the content of the current directory.\n"
        geom_missing_error += (
            "--------------------------------------------------------------\n"
        )
        raise FileNotFoundError(geom_missing_error) from exc
    

def check_nx_trajs() -> dict:
    """Check the status of each trajectory and set the maximum time step to
    read accordingly.

    .. note:: Tmax is extracted from 0/data/out.log file in traj_dir for the last timestep.
            Else is extracted from .json input file.
    
    If a two-columns file named 'trajs_tmax.dat' is available in the
              working directory, the data available for each trajectory will be
              collected until the tmax value defined in the file. Otherwise,
              the data will be read until the last step of the dynamics before
              any error message found in the output file.

    :return: A dictionary with the trajectory ID as the key and the tmax as the
             values.
    :rtype: dict
    """
    traj_tmax = {}
    traj_list = get_traj_dirs()
    if len(traj_list) == 0:
        return traj_tmax

    else: 
        for traj in traj_list:
            try:
                sh_log = traj + "/0/data/out.log"
                with open(sh_log, "r") as out:
                    lines = out.read().split("\n")
                    end_flag = "TERMINATED"
                            
                    time_lines = list(filter(lambda k: "Time:" in k, lines))
                    if time_lines:  # If we found any time lines
                        #tmax = float(time_lines[-1].split()[4])
                        tmax=float(time_lines[-1].split()[1])
                    #traj_tmax[traj] = tmax

            except FileNotFoundError:
                print("\n---------------------------------------")
                print("out.log file not found.")
                print("Check the {}/0/data/ directory.".format(traj))
                print("---------------------------------------\n")
                continue

    if not traj_tmax:  # If no trajectories were successfully processed
        config = read_nx_control(traj_list[0])
        tmax = config.get("tmax", 10000)
        traj_tmax = dict.fromkeys(traj_list, tmax)

    return traj_tmax