"""Auxiliary set of functions and constants used to process Newton-X data."""
# Author: Max Pinheiro Jr <maxjr82@gmail.com>
# Date: May 17 2021

import os
import glob

from typing import Tuple

import h5py
import numpy as np

#%% List of constants
BOHR_TO_ANG = 0.529177210903
HARTREE_TO_KCAL = 627.5096080305927
HARTREE_TO_eV = 27.211399
PROTON_MASS = 1822.888515

#%% Auxiliary functions


def get_traj_dirs() -> list:
    """Generate a list of TRAJ directories to be processed.

    :return: A list with the name of all 'TRAJXX' directories (sorted in ascending order)
             generated by the NX simulations available in the current directory.
    :rtype: list
    """
    dirs_list = glob.glob("TRAJ[0-9]*")
    dirs_list = sorted(dirs_list, key=lambda x: int(x.rsplit("TRAJ")[1]))
    return dirs_list


def get_nx_version(traj_dir: str) -> str:
    """Check Newton-X version.

    :param traj_dir: Name of the TRAJ directory in which the configuration file will be
                     verified to identify the NX version.
    :type traj_dir: str
    :return: Identifier of the NX version. It can be either 'cs' (Classical series) or 'ns'
             (New series).
    :rtype: str
    """
    nx_version = None
    if os.path.isdir(traj_dir):
        if os.path.isfile(traj_dir + "/" + "configuration.inp"):
            nx_version = "ns"
        elif os.path.isfile(traj_dir + "/" + "control.dyn"):
            nx_version = "cs"
        else:
            print("\nERROR: Newton-X version not recognized!\n")
    else:
        print("The {} directory does not exist.".format(traj_dir))
    return nx_version


def get_labels_masses(
    traj_dir: str, n_atoms: int = None
) -> Tuple[np.ndarray, np.ndarray]:
    """Extract the atom labels and atomic masses from the NX geometry input.

    :param traj_dir: Name of the TRAJ directory from which the geometry file
                     will be read.
    :type traj_dir: str
    :param n_atoms: If provided, the first n_atoms of the XYZ coordinates matrix will
                    be selected and returned, defaults to None.
    :type n_atoms: _type_, optional
    :return: Two separate numpy arrays containing the atom labels and the respective masses.
    :rtype: Tuple[np.ndarray, np.ndarray]
    """
    if os.path.isfile(traj_dir + "/geom"):
        # This is the standard geom input file in classical Newton-X
        nx_geom_file = traj_dir + "/geom"
    elif os.path.isfile(traj_dir + "/geom.orig"):
        # This is the file name for new Newton-X
        nx_geom_file = traj_dir + "/geom.orig"
    else:
        geom_missing_error = (
            "\n--------------------------------------------------------------\n"
        )
        geom_missing_error += (
            "ERROR:                                                       \n"
        )
        geom_missing_error += (
            "Newton-X geometry file not found.                            \n"
        )
        geom_missing_error += (
            "Check the content of the {} directory                        \n".format(
                traj_dir
            )
        )
        geom_missing_error += (
            "--------------------------------------------------------------\n"
        )
        raise FileNotFoundError(geom_missing_error)

    try:
        data = np.loadtxt(
            nx_geom_file,
            usecols=(0, 5),
            unpack=True,
            dtype={"names": ("labels", "masses"), "formats": ("U1", "float")},
        )
        atom_labels, atom_mass = data
        atom_mass *= PROTON_MASS
    except IndexError as ind_err:
        raise (ind_err)
    except ValueError as val_err:
        raise (val_err)

    if n_atoms:
        atom_labels = atom_labels[:n_atoms]
        atom_mass = atom_mass[:n_atoms]

    return (atom_labels, atom_mass)


def read_nx_control(traj_dir: str) -> dict:
    """Read and store the NX simulation settings from the configuration file.

    :param traj_dir: Name of the TRAJ directory from which the geometry file
                     will be read.
    :type traj_dir: str
    :return: Dictionary with all Newton-X keywords and corresponding values read from
             the control.dyn file (NX-CS) or from the configuration.inp file (NX-NS).
    :rtype: dict
    """
    control = {}
    if os.path.isfile(traj_dir + "/control.dyn"):
        control_input = traj_dir + "/control.dyn"
    elif os.path.isfile(traj_dir + "/configuration.inp"):
        control_input = traj_dir + "/configuration.inp"
    else:
        control_missing_error = (
            "--------------------------------------------------------------\n"
        )
        control_missing_error += (
            "ERROR:                                                       \n"
        )
        control_missing_error += (
            "Newton-X control file not found.                            \n"
        )
        control_missing_error += (
            "Check the content of the {} directory                        \n".format(
                traj_dir
            )
        )
        control_missing_error += (
            "--------------------------------------------------------------\n"
        )
        print(control_missing_error)
        return control

    with open(control_input, "r", encoding="utf-8") as nxinp:
        for line in nxinp:
            if len(line.split()) >= 3:
                keyword = line.split()[0]
                value = line.split("=")[1].split()[0]
                try:
                    control[keyword] = float(value)
                except ValueError:
                    control[keyword] = value

    return control


def read_h5_nx(traj_dir: str):
    """Read trajectory data from h5 file generated by Newton-X new series.

    :param traj_dir: Name of the TRAJ directory from which the geometry file
                     will be read.
    :type traj: str
    :return: H5py data object where trajectory data can be accessed via keywords,
             similarly to a dictionary.
    :rtype: h5py._hl.files.File
    """
    files = os.listdir(traj_dir + "/RESULTS")
    h5file = next((f for f in files if f.endswith(".h5")), None)
    if h5file:
        h5file = traj_dir + "/RESULTS/" + h5file
        data = h5py.File(h5file, "r")
    else:
        h5_missing_error = (
            "--------------------------------------------------------------\n"
        )
        h5_missing_error += (
            "ERROR:                                                       \n"
        )
        h5_missing_error += (
            "Newton-X control file not found.                            \n"
        )
        h5_missing_error += (
            "Check the content of the {} directory                        \n".format(
                traj_dir
            )
        )
        h5_missing_error += (
            "--------------------------------------------------------------\n"
        )
        print(h5_missing_error)
        return None

    return data


def get_num_atoms() -> int:
    """Get the number of atoms from a reference 'geom.xyz' file.

    :return: The number of atoms in a molecule or fragment of it.
    :rtype: int
    """
    try:
        n_atoms = int(open("geom.xyz").readline().rstrip())
        return n_atoms
    except FileNotFoundError as exc:
        geom_missing_error = (
            "\n--------------------------------------------------------------\n"
        )
        geom_missing_error += (
            "ERROR:                                                       \n"
        )
        geom_missing_error += (
            "Reference geometry file (geom.xyz) not found.                \n"
        )
        geom_missing_error += (
            "Check the content of the current directory.                     \n"
        )
        geom_missing_error += (
            "--------------------------------------------------------------\n"
        )
        raise FileNotFoundError(geom_missing_error) from exc


def check_nx_trajs() -> dict:
    """Check the status of each trajectory and set the maximum time step to read accordingly.

    .. note:: If a two-columns file named 'trajs_tmax.dat' is available in the working directory,
              the data available for each trajectory will be collected until the tmax value defined
              in the file. Otherwise, the data will be read until the last step of the dynamics
              before any error message found in the output file.

    :return: A dictionary with the trajectory ID as the key and the tmax as the values.
    :rtype: dict
    """
    traj_tmax = {}
    traj_list = get_traj_dirs()
    if len(traj_list) == 0:
        return traj_tmax

    if os.path.isfile("trajs_tmax.dat"):
        lines = open("trajs_tmax.dat", "r").readlines()
        for line in lines:
            traj = line.split()[0].strip()
            tmax = float(line.split()[1])
            if traj in traj_list:
                traj_tmax[traj] = tmax
    else:
        nx_version = get_nx_version(traj_list[0])
        if nx_version == "cs":
            for traj in traj_list:
                try:
                    nxlog = traj + "/RESULTS/nx.log"
                    out = open(nxlog, "r")
                except FileNotFoundError:
                    print("\n---------------------------------------")
                    print("nx.log file not found.")
                    print("Check the {}/RESULTS directory.".format(traj))
                    print("---------------------------------------\n")
                    continue

                lines = out.read().split("\n")
                t_last = list(filter(lambda k: "TIME" in k, lines))[-3:]
                end_flag = "NEWTON-X ends here"
                normal_run = any(end_flag in line for line in lines[-5:])
                step = -1 if normal_run else -2
                tmax = float(t_last[step].split()[4])
                traj_tmax[traj] = tmax
                out.close()
        else:
            config = read_nx_control(traj_list[0])
            tmax = config.get("tmax", 10000)
            traj_tmax = dict.fromkeys(traj_list, tmax)

    return traj_tmax
